apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-bot
automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: ci-runner
spec:
  serviceAccountName: ci-bot
  containers:
  - name: runner
    image: ci-tool
    env:
    - name: KUBE_TOKEN
      valueFrom:
        secretKeyRef:
          name: ci-bot-token
          key: token