apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ws-ports
spec:
  podSelector:
    matchLabels:
      app: websocket-server
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      portRange: 3000-4000